/**
 * Exobiology by boxel, from EDAstro's codex file (codex-data.csv: 4,909,402 logged entries,
 * 1,804,395 systems with biology; docs/perf/boxel_species_study.py, boxel_golden.py and
 * boxel_bio_rates_ts.py, 2026-10-05). Per mass code (`all`) and AA-A boxels only (`aaA`): `n`
 * systems with a biology entry logged, and how many of them hold each genus (`g:`) and species
 * (`sp:`). The share is of systems someone logged biology in, not of every system.
 *
 * `BOXEL_BIO_GOLDEN`: exact boxel positions (= letter combinations) where a genus or species is far
 * more common than in the rest of its mass code — clearing a Bonferroni threshold over 101,285 tests
 * and holding in both halves of the galaxy. [target, mass code, position, systems, hits, rest's share]
 */
import type { BoxelMassCodeRates } from "./boxelRates.js";

export type BoxelBioRates = Pick<BoxelMassCodeRates, "all" | "aaA">;

export const BOXEL_BIO_RATES: Readonly<Record<string, BoxelBioRates>> = {
  a: {
    all: {
      n: 27172,
      hits: {
        "g:Aleoida": 127,
        "g:Bacterium": 25265,
        "g:Bark Mound": 82,
        "g:Brain Tree": 138,
        "g:Cactoida": 323,
        "g:Clypeus": 88,
        "g:Concha": 78,
        "g:Electricae": 128,
        "g:Fonticulua": 1846,
        "g:Frutexa": 425,
        "g:Fumerola": 155,
        "g:Fungoida": 374,
        "g:Osseus": 307,
        "g:Recepta": 111,
        "g:Sinuous Tuber": 31,
        "g:Stratum": 1101,
        "g:Tubus": 203,
        "g:Tussock": 1016,
        "sp:Albidum Sinuous Tubers": 3,
        "sp:Aleoida Arcus": 6,
        "sp:Aleoida Coronamus": 20,
        "sp:Aleoida Gravis": 33,
        "sp:Aleoida Laminiae": 30,
        "sp:Aleoida Spica": 39,
        "sp:Aureum Brain Tree": 2,
        "sp:Bacterium Acies": 16531,
        "sp:Bacterium Alcyoneum": 432,
        "sp:Bacterium Aurasus": 481,
        "sp:Bacterium Bullaris": 95,
        "sp:Bacterium Cerbrus": 279,
        "sp:Bacterium Informem": 580,
        "sp:Bacterium Nebulus": 2657,
        "sp:Bacterium Omentum": 1095,
        "sp:Bacterium Scopulum": 795,
        "sp:Bacterium Tela": 2508,
        "sp:Bacterium Verrata": 831,
        "sp:Bacterium Vesicula": 1105,
        "sp:Bacterium Volu": 56,
        "sp:Bark Mounds": 82,
        "sp:Blatteum Sinuous Tubers": 3,
        "sp:Cactoida Cortexum": 77,
        "sp:Cactoida Lapis": 142,
        "sp:Cactoida Peperatis": 37,
        "sp:Cactoida Pullulanta": 30,
        "sp:Cactoida Vermis": 47,
        "sp:Caeruleum Sinuous Tubers": 2,
        "sp:Clypeus Margaritus": 88,
        "sp:Concha Labiata": 27,
        "sp:Concha Renibus": 52,
        "sp:Electricae Radialem": 128,
        "sp:Fonticulua Campestris": 1287,
        "sp:Fonticulua Digitos": 96,
        "sp:Fonticulua Fluctus": 12,
        "sp:Fonticulua Lapida": 370,
        "sp:Fonticulua Segmentatus": 37,
        "sp:Fonticulua Upupam": 101,
        "sp:Frutexa Acus": 3,
        "sp:Frutexa Collum": 2,
        "sp:Frutexa Flabellum": 2,
        "sp:Frutexa Flammasis": 2,
        "sp:Frutexa Metallicum": 416,
        "sp:Fumerola Aquatis": 69,
        "sp:Fumerola Carbosis": 40,
        "sp:Fumerola Extremus": 2,
        "sp:Fumerola Nitris": 44,
        "sp:Fungoida Bullarum": 107,
        "sp:Fungoida Gelata": 28,
        "sp:Fungoida Setisis": 206,
        "sp:Fungoida Stabitis": 39,
        "sp:Lindigoticum Sinuous Tubers": 3,
        "sp:Lividum Brain Tree": 2,
        "sp:Osseus Cornibus": 8,
        "sp:Osseus Discus": 24,
        "sp:Osseus Fractus": 37,
        "sp:Osseus Pellebantus": 7,
        "sp:Osseus Pumice": 152,
        "sp:Osseus Spiralis": 89,
        "sp:Ostrinum Brain Tree": 4,
        "sp:Prasinum Sinuous Tubers": 8,
        "sp:Recepta Conditivus": 41,
        "sp:Recepta Deltahedronix": 16,
        "sp:Recepta Umbrux": 56,
        "sp:Roseum Brain Tree": 138,
        "sp:Roseum Sinuous Tubers": 19,
        "sp:Stratum Excutitus": 1,
        "sp:Stratum Limaxus": 1,
        "sp:Stratum Paleas": 3,
        "sp:Stratum Tectonicas": 1096,
        "sp:Tubus Cavas": 1,
        "sp:Tubus Compagibus": 6,
        "sp:Tubus Rosarium": 1,
        "sp:Tubus Sororibus": 196,
        "sp:Tussock Albata": 85,
        "sp:Tussock Capillum": 97,
        "sp:Tussock Caputus": 82,
        "sp:Tussock Catena": 44,
        "sp:Tussock Cultro": 292,
        "sp:Tussock Divisa": 62,
        "sp:Tussock Ignis": 138,
        "sp:Tussock Pennata": 10,
        "sp:Tussock Pennatis": 50,
        "sp:Tussock Propagito": 81,
        "sp:Tussock Serrati": 47,
        "sp:Tussock Stigmasis": 2,
        "sp:Tussock Triticum": 29,
        "sp:Tussock Ventusa": 27,
        "sp:Tussock Virgam": 59,
        "sp:Violaceum Sinuous Tubers": 3,
        "sp:Viride Sinuous Tubers": 2,
      },
    },
    aaA: {
      n: 12,
      hits: {
        "g:Bacterium": 11,
        "g:Fonticulua": 1,
        "sp:Bacterium Acies": 10,
        "sp:Bacterium Omentum": 1,
        "sp:Fonticulua Upupam": 1,
      },
    },
  },
  b: {
    all: {
      n: 450492,
      hits: {
        "g:Aleoida": 11336,
        "g:Anemone": 1,
        "g:Bacterium": 322189,
        "g:Bark Mound": 4503,
        "g:Brain Tree": 5950,
        "g:Cactoida": 19226,
        "g:Clypeus": 6776,
        "g:Concha": 6421,
        "g:Crystalline Shard": 29,
        "g:Electricae": 8474,
        "g:Fonticulua": 127518,
        "g:Frutexa": 35106,
        "g:Fumerola": 11302,
        "g:Fungoida": 41014,
        "g:Osseus": 34817,
        "g:Recepta": 4909,
        "g:Sinuous Tuber": 747,
        "g:Stratum": 82619,
        "g:Tubus": 12584,
        "g:Tussock": 70880,
        "sp:Albidum Sinuous Tubers": 119,
        "sp:Aleoida Arcus": 1470,
        "sp:Aleoida Coronamus": 2345,
        "sp:Aleoida Gravis": 2232,
        "sp:Aleoida Laminiae": 3002,
        "sp:Aleoida Spica": 2431,
        "sp:Aureum Brain Tree": 279,
        "sp:Bacterium Acies": 63437,
        "sp:Bacterium Alcyoneum": 28492,
        "sp:Bacterium Aurasus": 34787,
        "sp:Bacterium Bullaris": 18512,
        "sp:Bacterium Cerbrus": 32288,
        "sp:Bacterium Informem": 46804,
        "sp:Bacterium Nebulus": 1539,
        "sp:Bacterium Omentum": 5107,
        "sp:Bacterium Scopulum": 3650,
        "sp:Bacterium Tela": 19404,
        "sp:Bacterium Verrata": 5574,
        "sp:Bacterium Vesicula": 101308,
        "sp:Bacterium Volu": 3718,
        "sp:Bark Mounds": 4503,
        "sp:Blatteum Sinuous Tubers": 80,
        "sp:Cactoida Cortexum": 4579,
        "sp:Cactoida Lapis": 8275,
        "sp:Cactoida Peperatis": 2297,
        "sp:Cactoida Pullulanta": 1746,
        "sp:Cactoida Vermis": 3002,
        "sp:Caeruleum Sinuous Tubers": 118,
        "sp:Clypeus Lacrimam": 764,
        "sp:Clypeus Margaritus": 6016,
        "sp:Clypeus Speculumi": 1,
        "sp:Concha Aureolas": 119,
        "sp:Concha Biconcavis": 203,
        "sp:Concha Labiata": 1059,
        "sp:Concha Renibus": 5083,
        "sp:Crystalline Shards": 29,
        "sp:Electricae Radialem": 8474,
        "sp:Fonticulua Campestris": 88022,
        "sp:Fonticulua Digitos": 12342,
        "sp:Fonticulua Fluctus": 171,
        "sp:Fonticulua Lapida": 21815,
        "sp:Fonticulua Segmentatus": 1243,
        "sp:Fonticulua Upupam": 7394,
        "sp:Frutexa Acus": 3783,
        "sp:Frutexa Collum": 226,
        "sp:Frutexa Fera": 460,
        "sp:Frutexa Flabellum": 3521,
        "sp:Frutexa Flammasis": 979,
        "sp:Frutexa Metallicum": 26682,
        "sp:Frutexa Sponsae": 122,
        "sp:Fumerola Aquatis": 3849,
        "sp:Fumerola Carbosis": 2608,
        "sp:Fumerola Extremus": 192,
        "sp:Fumerola Nitris": 4757,
        "sp:Fungoida Bullarum": 18332,
        "sp:Fungoida Gelata": 2906,
        "sp:Fungoida Setisis": 17070,
        "sp:Fungoida Stabitis": 3244,
        "sp:Gypseeum Brain Tree": 96,
        "sp:Lindigoticum Brain Tree": 20,
        "sp:Lindigoticum Sinuous Tubers": 66,
        "sp:Lividum Brain Tree": 866,
        "sp:Osseus Cornibus": 283,
        "sp:Osseus Discus": 1830,
        "sp:Osseus Fractus": 945,
        "sp:Osseus Pellebantus": 219,
        "sp:Osseus Pumice": 29058,
        "sp:Osseus Spiralis": 2805,
        "sp:Ostrinum Brain Tree": 974,
        "sp:Prasinum Sinuous Tubers": 327,
        "sp:Puniceum Brain Tree": 216,
        "sp:Recepta Conditivus": 1829,
        "sp:Recepta Deltahedronix": 424,
        "sp:Recepta Umbrux": 2735,
        "sp:Roseum Bioluminescent Anemone": 1,
        "sp:Roseum Brain Tree": 4665,
        "sp:Roseum Sinuous Tubers": 298,
        "sp:Stratum Cucumisis": 336,
        "sp:Stratum Excutitus": 1676,
        "sp:Stratum Frigus": 81,
        "sp:Stratum Laminamus": 802,
        "sp:Stratum Limaxus": 588,
        "sp:Stratum Paleas": 6418,
        "sp:Stratum Tectonicas": 74194,
        "sp:Tubus Cavas": 725,
        "sp:Tubus Compagibus": 2249,
        "sp:Tubus Conifer": 545,
        "sp:Tubus Rosarium": 707,
        "sp:Tubus Sororibus": 8425,
        "sp:Tussock Albata": 5358,
        "sp:Tussock Capillum": 13279,
        "sp:Tussock Caputus": 5842,
        "sp:Tussock Catena": 3907,
        "sp:Tussock Cultro": 14804,
        "sp:Tussock Divisa": 5528,
        "sp:Tussock Ignis": 7355,
        "sp:Tussock Pennata": 800,
        "sp:Tussock Pennatis": 2883,
        "sp:Tussock Propagito": 5567,
        "sp:Tussock Serrati": 2906,
        "sp:Tussock Stigmasis": 290,
        "sp:Tussock Triticum": 2164,
        "sp:Tussock Ventusa": 1906,
        "sp:Tussock Virgam": 4164,
        "sp:Violaceum Sinuous Tubers": 47,
        "sp:Viride Brain Tree": 90,
        "sp:Viride Sinuous Tubers": 25,
      },
    },
    aaA: {
      n: 90,
      hits: {
        "g:Bacterium": 65,
        "g:Bark Mound": 1,
        "g:Cactoida": 6,
        "g:Clypeus": 3,
        "g:Concha": 2,
        "g:Electricae": 1,
        "g:Fonticulua": 39,
        "g:Frutexa": 9,
        "g:Fumerola": 4,
        "g:Fungoida": 14,
        "g:Osseus": 10,
        "g:Recepta": 1,
        "g:Sinuous Tuber": 2,
        "g:Stratum": 15,
        "g:Tubus": 3,
        "g:Tussock": 15,
        "sp:Bacterium Acies": 11,
        "sp:Bacterium Alcyoneum": 9,
        "sp:Bacterium Aurasus": 6,
        "sp:Bacterium Bullaris": 3,
        "sp:Bacterium Cerbrus": 5,
        "sp:Bacterium Informem": 7,
        "sp:Bacterium Omentum": 1,
        "sp:Bacterium Scopulum": 1,
        "sp:Bacterium Tela": 8,
        "sp:Bacterium Verrata": 1,
        "sp:Bacterium Vesicula": 23,
        "sp:Bacterium Volu": 3,
        "sp:Bark Mounds": 1,
        "sp:Cactoida Lapis": 1,
        "sp:Cactoida Peperatis": 1,
        "sp:Cactoida Pullulanta": 2,
        "sp:Cactoida Vermis": 2,
        "sp:Clypeus Lacrimam": 1,
        "sp:Clypeus Margaritus": 2,
        "sp:Concha Biconcavis": 1,
        "sp:Concha Renibus": 1,
        "sp:Electricae Radialem": 1,
        "sp:Fonticulua Campestris": 28,
        "sp:Fonticulua Digitos": 4,
        "sp:Fonticulua Lapida": 5,
        "sp:Fonticulua Segmentatus": 3,
        "sp:Fonticulua Upupam": 1,
        "sp:Frutexa Flabellum": 1,
        "sp:Frutexa Metallicum": 8,
        "sp:Fumerola Aquatis": 1,
        "sp:Fumerola Carbosis": 1,
        "sp:Fumerola Nitris": 2,
        "sp:Fungoida Bullarum": 6,
        "sp:Fungoida Gelata": 2,
        "sp:Fungoida Setisis": 6,
        "sp:Osseus Discus": 1,
        "sp:Osseus Pumice": 8,
        "sp:Osseus Spiralis": 1,
        "sp:Recepta Umbrux": 1,
        "sp:Roseum Sinuous Tubers": 2,
        "sp:Stratum Paleas": 3,
        "sp:Stratum Tectonicas": 13,
        "sp:Tubus Cavas": 1,
        "sp:Tubus Sororibus": 2,
        "sp:Tussock Albata": 1,
        "sp:Tussock Capillum": 1,
        "sp:Tussock Caputus": 1,
        "sp:Tussock Catena": 2,
        "sp:Tussock Cultro": 4,
        "sp:Tussock Divisa": 2,
        "sp:Tussock Ignis": 2,
        "sp:Tussock Triticum": 1,
        "sp:Tussock Ventusa": 1,
        "sp:Tussock Virgam": 1,
      },
    },
  },
  c: {
    all: {
      n: 614928,
      hits: {
        "g:Aleoida": 54010,
        "g:Anemone": 1,
        "g:Bacterium": 387746,
        "g:Bark Mound": 5973,
        "g:Brain Tree": 5283,
        "g:Cactoida": 23730,
        "g:Clypeus": 18611,
        "g:Concha": 57921,
        "g:Crystalline Shard": 3839,
        "g:Electricae": 5768,
        "g:Fonticulua": 104011,
        "g:Frutexa": 54284,
        "g:Fumerola": 12413,
        "g:Fungoida": 85802,
        "g:Osseus": 83627,
        "g:Recepta": 7877,
        "g:Sinuous Tuber": 3301,
        "g:Stratum": 206256,
        "g:Tubus": 71404,
        "g:Tussock": 197606,
        "sp:Albidum Sinuous Tubers": 530,
        "sp:Aleoida Arcus": 12796,
        "sp:Aleoida Coronamus": 16333,
        "sp:Aleoida Gravis": 7259,
        "sp:Aleoida Laminiae": 11772,
        "sp:Aleoida Spica": 7621,
        "sp:Aureum Brain Tree": 312,
        "sp:Bacterium Acies": 14153,
        "sp:Bacterium Alcyoneum": 75312,
        "sp:Bacterium Aurasus": 122219,
        "sp:Bacterium Bullaris": 32314,
        "sp:Bacterium Cerbrus": 69828,
        "sp:Bacterium Informem": 44037,
        "sp:Bacterium Nebulus": 50,
        "sp:Bacterium Omentum": 2169,
        "sp:Bacterium Scopulum": 1305,
        "sp:Bacterium Tela": 19281,
        "sp:Bacterium Verrata": 1524,
        "sp:Bacterium Vesicula": 59909,
        "sp:Bacterium Volu": 4075,
        "sp:Bark Mounds": 5973,
        "sp:Blatteum Sinuous Tubers": 95,
        "sp:Cactoida Cortexum": 6159,
        "sp:Cactoida Lapis": 9064,
        "sp:Cactoida Peperatis": 4057,
        "sp:Cactoida Pullulanta": 2947,
        "sp:Cactoida Vermis": 2406,
        "sp:Caeruleum Sinuous Tubers": 732,
        "sp:Clypeus Lacrimam": 10048,
        "sp:Clypeus Margaritus": 7712,
        "sp:Clypeus Speculumi": 863,
        "sp:Concha Aureolas": 9197,
        "sp:Concha Biconcavis": 195,
        "sp:Concha Labiata": 27491,
        "sp:Concha Renibus": 21995,
        "sp:Crystalline Shards": 3839,
        "sp:Electricae Radialem": 5768,
        "sp:Fonticulua Campestris": 56474,
        "sp:Fonticulua Digitos": 23032,
        "sp:Fonticulua Fluctus": 271,
        "sp:Fonticulua Lapida": 17761,
        "sp:Fonticulua Segmentatus": 1525,
        "sp:Fonticulua Upupam": 7987,
        "sp:Frutexa Acus": 14430,
        "sp:Frutexa Collum": 561,
        "sp:Frutexa Fera": 4211,
        "sp:Frutexa Flabellum": 12696,
        "sp:Frutexa Flammasis": 5444,
        "sp:Frutexa Metallicum": 18597,
        "sp:Frutexa Sponsae": 694,
        "sp:Fumerola Aquatis": 3061,
        "sp:Fumerola Carbosis": 3616,
        "sp:Fumerola Extremus": 1783,
        "sp:Fumerola Nitris": 4046,
        "sp:Fungoida Bullarum": 4498,
        "sp:Fungoida Gelata": 20303,
        "sp:Fungoida Setisis": 49762,
        "sp:Fungoida Stabitis": 15158,
        "sp:Gypseeum Brain Tree": 337,
        "sp:Lindigoticum Brain Tree": 18,
        "sp:Lindigoticum Sinuous Tubers": 79,
        "sp:Lividum Brain Tree": 655,
        "sp:Osseus Cornibus": 6083,
        "sp:Osseus Discus": 3469,
        "sp:Osseus Fractus": 17169,
        "sp:Osseus Pellebantus": 4828,
        "sp:Osseus Pumice": 9962,
        "sp:Osseus Spiralis": 46024,
        "sp:Ostrinum Brain Tree": 1307,
        "sp:Prasinum Bioluminescent Anemone": 1,
        "sp:Prasinum Sinuous Tubers": 1365,
        "sp:Puniceum Brain Tree": 357,
        "sp:Recepta Conditivus": 2152,
        "sp:Recepta Deltahedronix": 1732,
        "sp:Recepta Umbrux": 4134,
        "sp:Roseum Brain Tree": 3454,
        "sp:Roseum Sinuous Tubers": 1568,
        "sp:Stratum Cucumisis": 4275,
        "sp:Stratum Excutitus": 17005,
        "sp:Stratum Frigus": 1085,
        "sp:Stratum Laminamus": 6739,
        "sp:Stratum Limaxus": 6400,
        "sp:Stratum Paleas": 61089,
        "sp:Stratum Tectonicas": 118793,
        "sp:Tubus Cavas": 14086,
        "sp:Tubus Compagibus": 30039,
        "sp:Tubus Conifer": 11395,
        "sp:Tubus Rosarium": 11031,
        "sp:Tubus Sororibus": 8442,
        "sp:Tussock Albata": 19049,
        "sp:Tussock Capillum": 5451,
        "sp:Tussock Caputus": 19725,
        "sp:Tussock Catena": 10744,
        "sp:Tussock Cultro": 36732,
        "sp:Tussock Divisa": 15423,
        "sp:Tussock Ignis": 28832,
        "sp:Tussock Pennata": 4529,
        "sp:Tussock Pennatis": 17534,
        "sp:Tussock Propagito": 28380,
        "sp:Tussock Serrati": 13867,
        "sp:Tussock Stigmasis": 2312,
        "sp:Tussock Triticum": 6896,
        "sp:Tussock Ventusa": 9196,
        "sp:Tussock Virgam": 4971,
        "sp:Violaceum Sinuous Tubers": 65,
        "sp:Viride Brain Tree": 271,
        "sp:Viride Sinuous Tubers": 35,
      },
    },
    aaA: {
      n: 248,
      hits: {
        "g:Aleoida": 13,
        "g:Bacterium": 182,
        "g:Cactoida": 7,
        "g:Clypeus": 5,
        "g:Concha": 19,
        "g:Crystalline Shard": 3,
        "g:Electricae": 1,
        "g:Fonticulua": 40,
        "g:Frutexa": 20,
        "g:Fumerola": 4,
        "g:Fungoida": 35,
        "g:Osseus": 29,
        "g:Recepta": 4,
        "g:Sinuous Tuber": 2,
        "g:Stratum": 90,
        "g:Tubus": 27,
        "g:Tussock": 71,
        "sp:Albidum Sinuous Tubers": 1,
        "sp:Aleoida Arcus": 2,
        "sp:Aleoida Coronamus": 4,
        "sp:Aleoida Gravis": 3,
        "sp:Aleoida Laminiae": 2,
        "sp:Aleoida Spica": 2,
        "sp:Bacterium Acies": 15,
        "sp:Bacterium Alcyoneum": 38,
        "sp:Bacterium Aurasus": 52,
        "sp:Bacterium Bullaris": 14,
        "sp:Bacterium Cerbrus": 37,
        "sp:Bacterium Informem": 21,
        "sp:Bacterium Omentum": 2,
        "sp:Bacterium Scopulum": 1,
        "sp:Bacterium Tela": 10,
        "sp:Bacterium Vesicula": 31,
        "sp:Bacterium Volu": 3,
        "sp:Cactoida Cortexum": 3,
        "sp:Cactoida Lapis": 1,
        "sp:Cactoida Peperatis": 1,
        "sp:Cactoida Pullulanta": 2,
        "sp:Clypeus Lacrimam": 1,
        "sp:Clypeus Margaritus": 3,
        "sp:Clypeus Speculumi": 1,
        "sp:Concha Labiata": 14,
        "sp:Concha Renibus": 6,
        "sp:Crystalline Shards": 3,
        "sp:Electricae Radialem": 1,
        "sp:Fonticulua Campestris": 14,
        "sp:Fonticulua Digitos": 13,
        "sp:Fonticulua Fluctus": 1,
        "sp:Fonticulua Lapida": 10,
        "sp:Fonticulua Segmentatus": 1,
        "sp:Fonticulua Upupam": 3,
        "sp:Frutexa Acus": 4,
        "sp:Frutexa Fera": 4,
        "sp:Frutexa Flabellum": 4,
        "sp:Frutexa Flammasis": 2,
        "sp:Frutexa Metallicum": 7,
        "sp:Fumerola Carbosis": 1,
        "sp:Fumerola Nitris": 3,
        "sp:Fungoida Bullarum": 2,
        "sp:Fungoida Gelata": 9,
        "sp:Fungoida Setisis": 23,
        "sp:Fungoida Stabitis": 4,
        "sp:Osseus Cornibus": 4,
        "sp:Osseus Fractus": 5,
        "sp:Osseus Pumice": 2,
        "sp:Osseus Spiralis": 20,
        "sp:Prasinum Sinuous Tubers": 2,
        "sp:Recepta Conditivus": 1,
        "sp:Recepta Deltahedronix": 1,
        "sp:Recepta Umbrux": 2,
        "sp:Roseum Sinuous Tubers": 1,
        "sp:Stratum Cucumisis": 1,
        "sp:Stratum Excutitus": 6,
        "sp:Stratum Frigus": 2,
        "sp:Stratum Laminamus": 1,
        "sp:Stratum Paleas": 24,
        "sp:Stratum Tectonicas": 59,
        "sp:Tubus Cavas": 5,
        "sp:Tubus Compagibus": 13,
        "sp:Tubus Conifer": 6,
        "sp:Tubus Rosarium": 4,
        "sp:Tubus Sororibus": 1,
        "sp:Tussock Albata": 5,
        "sp:Tussock Capillum": 2,
        "sp:Tussock Caputus": 11,
        "sp:Tussock Catena": 4,
        "sp:Tussock Cultro": 17,
        "sp:Tussock Divisa": 5,
        "sp:Tussock Ignis": 16,
        "sp:Tussock Pennatis": 5,
        "sp:Tussock Propagito": 8,
        "sp:Tussock Serrati": 4,
        "sp:Tussock Stigmasis": 2,
        "sp:Tussock Triticum": 1,
        "sp:Tussock Ventusa": 2,
      },
    },
  },
  d: {
    all: {
      n: 642235,
      hits: {
        "g:Aleoida": 73909,
        "g:Amphora Plant": 1454,
        "g:Anemone": 2,
        "g:Bacterium": 384594,
        "g:Bark Mound": 11426,
        "g:Brain Tree": 10303,
        "g:Cactoida": 94521,
        "g:Clypeus": 33604,
        "g:Concha": 110385,
        "g:Crystalline Shard": 6373,
        "g:Electricae": 9264,
        "g:Fonticulua": 46564,
        "g:Frutexa": 149370,
        "g:Fumerola": 3452,
        "g:Fungoida": 116391,
        "g:Osseus": 136439,
        "g:Recepta": 11496,
        "g:Sinuous Tuber": 7109,
        "g:Stratum": 215005,
        "g:Tubus": 98369,
        "g:Tussock": 221571,
        "sp:Albidum Sinuous Tubers": 1233,
        "sp:Aleoida Arcus": 17323,
        "sp:Aleoida Coronamus": 22791,
        "sp:Aleoida Gravis": 8311,
        "sp:Aleoida Laminiae": 18855,
        "sp:Aleoida Spica": 10805,
        "sp:Amphora Plants": 1454,
        "sp:Aureum Brain Tree": 545,
        "sp:Bacterium Acies": 4927,
        "sp:Bacterium Alcyoneum": 98965,
        "sp:Bacterium Aurasus": 153880,
        "sp:Bacterium Bullaris": 6239,
        "sp:Bacterium Cerbrus": 97402,
        "sp:Bacterium Informem": 14801,
        "sp:Bacterium Nebulus": 149,
        "sp:Bacterium Omentum": 692,
        "sp:Bacterium Scopulum": 461,
        "sp:Bacterium Tela": 28569,
        "sp:Bacterium Verrata": 822,
        "sp:Bacterium Vesicula": 27179,
        "sp:Bacterium Volu": 5228,
        "sp:Bark Mounds": 11426,
        "sp:Blatteum Bioluminescent Anemone": 1,
        "sp:Blatteum Sinuous Tubers": 253,
        "sp:Cactoida Cortexum": 23972,
        "sp:Cactoida Lapis": 33213,
        "sp:Cactoida Peperatis": 17189,
        "sp:Cactoida Pullulanta": 11338,
        "sp:Cactoida Vermis": 13353,
        "sp:Caeruleum Sinuous Tubers": 1521,
        "sp:Clypeus Lacrimam": 19728,
        "sp:Clypeus Margaritus": 6095,
        "sp:Clypeus Speculumi": 7881,
        "sp:Concha Aureolas": 22215,
        "sp:Concha Biconcavis": 66,
        "sp:Concha Labiata": 56502,
        "sp:Concha Renibus": 35532,
        "sp:Crystalline Shards": 6373,
        "sp:Electricae Pluma": 7505,
        "sp:Electricae Radialem": 1759,
        "sp:Fonticulua Campestris": 33348,
        "sp:Fonticulua Digitos": 4859,
        "sp:Fonticulua Fluctus": 511,
        "sp:Fonticulua Lapida": 5221,
        "sp:Fonticulua Segmentatus": 502,
        "sp:Fonticulua Upupam": 3428,
        "sp:Frutexa Acus": 46678,
        "sp:Frutexa Collum": 2246,
        "sp:Frutexa Fera": 15710,
        "sp:Frutexa Flabellum": 44144,
        "sp:Frutexa Flammasis": 20019,
        "sp:Frutexa Metallicum": 23526,
        "sp:Frutexa Sponsae": 6393,
        "sp:Fumerola Aquatis": 1188,
        "sp:Fumerola Carbosis": 782,
        "sp:Fumerola Extremus": 690,
        "sp:Fumerola Nitris": 824,
        "sp:Fungoida Bullarum": 2543,
        "sp:Fungoida Gelata": 33931,
        "sp:Fungoida Setisis": 65122,
        "sp:Fungoida Stabitis": 21623,
        "sp:Gypseeum Brain Tree": 1439,
        "sp:Lindigoticum Brain Tree": 53,
        "sp:Lindigoticum Sinuous Tubers": 360,
        "sp:Lividum Brain Tree": 1416,
        "sp:Osseus Cornibus": 9609,
        "sp:Osseus Discus": 8517,
        "sp:Osseus Fractus": 29209,
        "sp:Osseus Pellebantus": 9382,
        "sp:Osseus Pumice": 4101,
        "sp:Osseus Spiralis": 84382,
        "sp:Ostrinum Brain Tree": 1764,
        "sp:Prasinum Sinuous Tubers": 3245,
        "sp:Puniceum Brain Tree": 1505,
        "sp:Recepta Conditivus": 3254,
        "sp:Recepta Deltahedronix": 2634,
        "sp:Recepta Umbrux": 5699,
        "sp:Roseum Brain Tree": 7003,
        "sp:Roseum Sinuous Tubers": 3004,
        "sp:Rubeum Bioluminescent Anemone": 2,
        "sp:Stratum Araneamus": 11894,
        "sp:Stratum Cucumisis": 12971,
        "sp:Stratum Excutitus": 19152,
        "sp:Stratum Frigus": 3421,
        "sp:Stratum Laminamus": 9533,
        "sp:Stratum Limaxus": 8289,
        "sp:Stratum Paleas": 80816,
        "sp:Stratum Tectonicas": 84114,
        "sp:Tubus Cavas": 23282,
        "sp:Tubus Compagibus": 42151,
        "sp:Tubus Conifer": 15107,
        "sp:Tubus Rosarium": 20373,
        "sp:Tubus Sororibus": 5317,
        "sp:Tussock Albata": 19062,
        "sp:Tussock Capillum": 3266,
        "sp:Tussock Caputus": 21656,
        "sp:Tussock Catena": 17476,
        "sp:Tussock Cultro": 39233,
        "sp:Tussock Divisa": 16321,
        "sp:Tussock Ignis": 31985,
        "sp:Tussock Pennata": 7446,
        "sp:Tussock Pennatis": 20817,
        "sp:Tussock Propagito": 35614,
        "sp:Tussock Serrati": 14972,
        "sp:Tussock Stigmasis": 3496,
        "sp:Tussock Triticum": 7626,
        "sp:Tussock Ventusa": 12537,
        "sp:Tussock Virgam": 9368,
        "sp:Violaceum Sinuous Tubers": 178,
        "sp:Viride Brain Tree": 122,
        "sp:Viride Sinuous Tubers": 160,
      },
    },
    aaA: {
      n: 955,
      hits: {
        "g:Aleoida": 106,
        "g:Amphora Plant": 2,
        "g:Bacterium": 551,
        "g:Bark Mound": 4,
        "g:Brain Tree": 2,
        "g:Cactoida": 118,
        "g:Clypeus": 56,
        "g:Concha": 149,
        "g:Crystalline Shard": 15,
        "g:Electricae": 7,
        "g:Fonticulua": 70,
        "g:Frutexa": 187,
        "g:Fumerola": 4,
        "g:Fungoida": 161,
        "g:Osseus": 181,
        "g:Recepta": 24,
        "g:Sinuous Tuber": 33,
        "g:Stratum": 289,
        "g:Tubus": 123,
        "g:Tussock": 298,
        "sp:Albidum Sinuous Tubers": 8,
        "sp:Aleoida Arcus": 26,
        "sp:Aleoida Coronamus": 28,
        "sp:Aleoida Gravis": 12,
        "sp:Aleoida Laminiae": 23,
        "sp:Aleoida Spica": 20,
        "sp:Amphora Plants": 2,
        "sp:Bacterium Acies": 11,
        "sp:Bacterium Alcyoneum": 137,
        "sp:Bacterium Aurasus": 197,
        "sp:Bacterium Bullaris": 8,
        "sp:Bacterium Cerbrus": 147,
        "sp:Bacterium Informem": 21,
        "sp:Bacterium Nebulus": 2,
        "sp:Bacterium Omentum": 1,
        "sp:Bacterium Tela": 45,
        "sp:Bacterium Verrata": 1,
        "sp:Bacterium Vesicula": 48,
        "sp:Bacterium Volu": 8,
        "sp:Bark Mounds": 4,
        "sp:Cactoida Cortexum": 24,
        "sp:Cactoida Lapis": 30,
        "sp:Cactoida Peperatis": 28,
        "sp:Cactoida Pullulanta": 19,
        "sp:Cactoida Vermis": 21,
        "sp:Caeruleum Sinuous Tubers": 9,
        "sp:Clypeus Lacrimam": 32,
        "sp:Clypeus Margaritus": 13,
        "sp:Clypeus Speculumi": 11,
        "sp:Concha Aureolas": 28,
        "sp:Concha Labiata": 74,
        "sp:Concha Renibus": 52,
        "sp:Crystalline Shards": 15,
        "sp:Electricae Pluma": 7,
        "sp:Fonticulua Campestris": 51,
        "sp:Fonticulua Digitos": 6,
        "sp:Fonticulua Lapida": 6,
        "sp:Fonticulua Upupam": 8,
        "sp:Frutexa Acus": 50,
        "sp:Frutexa Collum": 4,
        "sp:Frutexa Fera": 29,
        "sp:Frutexa Flabellum": 51,
        "sp:Frutexa Flammasis": 32,
        "sp:Frutexa Metallicum": 38,
        "sp:Frutexa Sponsae": 7,
        "sp:Fumerola Aquatis": 1,
        "sp:Fumerola Carbosis": 1,
        "sp:Fumerola Nitris": 2,
        "sp:Fungoida Bullarum": 1,
        "sp:Fungoida Gelata": 42,
        "sp:Fungoida Setisis": 94,
        "sp:Fungoida Stabitis": 32,
        "sp:Lindigoticum Sinuous Tubers": 8,
        "sp:Osseus Cornibus": 22,
        "sp:Osseus Discus": 14,
        "sp:Osseus Fractus": 29,
        "sp:Osseus Pellebantus": 16,
        "sp:Osseus Pumice": 3,
        "sp:Osseus Spiralis": 105,
        "sp:Ostrinum Brain Tree": 2,
        "sp:Prasinum Sinuous Tubers": 12,
        "sp:Recepta Conditivus": 11,
        "sp:Recepta Deltahedronix": 2,
        "sp:Recepta Umbrux": 11,
        "sp:Roseum Brain Tree": 1,
        "sp:Roseum Sinuous Tubers": 16,
        "sp:Stratum Araneamus": 21,
        "sp:Stratum Cucumisis": 13,
        "sp:Stratum Excutitus": 22,
        "sp:Stratum Frigus": 7,
        "sp:Stratum Laminamus": 11,
        "sp:Stratum Limaxus": 6,
        "sp:Stratum Paleas": 94,
        "sp:Stratum Tectonicas": 128,
        "sp:Tubus Cavas": 40,
        "sp:Tubus Compagibus": 42,
        "sp:Tubus Conifer": 29,
        "sp:Tubus Rosarium": 23,
        "sp:Tubus Sororibus": 4,
        "sp:Tussock Albata": 21,
        "sp:Tussock Capillum": 2,
        "sp:Tussock Caputus": 22,
        "sp:Tussock Catena": 22,
        "sp:Tussock Cultro": 55,
        "sp:Tussock Divisa": 19,
        "sp:Tussock Ignis": 29,
        "sp:Tussock Pennata": 12,
        "sp:Tussock Pennatis": 47,
        "sp:Tussock Propagito": 51,
        "sp:Tussock Serrati": 18,
        "sp:Tussock Stigmasis": 6,
        "sp:Tussock Triticum": 11,
        "sp:Tussock Ventusa": 10,
        "sp:Tussock Virgam": 15,
      },
    },
  },
  e: {
    all: {
      n: 35966,
      hits: {
        "g:Aleoida": 1335,
        "g:Amphora Plant": 45,
        "g:Anemone": 19676,
        "g:Bacterium": 10380,
        "g:Bark Mound": 863,
        "g:Brain Tree": 213,
        "g:Cactoida": 1612,
        "g:Clypeus": 2125,
        "g:Concha": 3199,
        "g:Crystalline Shard": 75,
        "g:Electricae": 903,
        "g:Fonticulua": 1750,
        "g:Frutexa": 3564,
        "g:Fumerola": 537,
        "g:Fungoida": 3063,
        "g:Osseus": 2818,
        "g:Recepta": 494,
        "g:Sinuous Tuber": 622,
        "g:Stratum": 3027,
        "g:Tubus": 1321,
        "g:Tussock": 3104,
        "sp:Albidum Sinuous Tubers": 113,
        "sp:Aleoida Arcus": 299,
        "sp:Aleoida Coronamus": 435,
        "sp:Aleoida Gravis": 164,
        "sp:Aleoida Laminiae": 336,
        "sp:Aleoida Spica": 198,
        "sp:Amphora Plants": 45,
        "sp:Aureum Brain Tree": 13,
        "sp:Bacterium Acies": 469,
        "sp:Bacterium Alcyoneum": 1312,
        "sp:Bacterium Aurasus": 2334,
        "sp:Bacterium Bullaris": 338,
        "sp:Bacterium Cerbrus": 3483,
        "sp:Bacterium Informem": 686,
        "sp:Bacterium Nebulus": 36,
        "sp:Bacterium Omentum": 54,
        "sp:Bacterium Scopulum": 35,
        "sp:Bacterium Tela": 1993,
        "sp:Bacterium Verrata": 53,
        "sp:Bacterium Vesicula": 992,
        "sp:Bacterium Volu": 164,
        "sp:Bark Mounds": 863,
        "sp:Blatteum Bioluminescent Anemone": 8918,
        "sp:Blatteum Sinuous Tubers": 34,
        "sp:Cactoida Cortexum": 264,
        "sp:Cactoida Lapis": 303,
        "sp:Cactoida Peperatis": 288,
        "sp:Cactoida Pullulanta": 102,
        "sp:Cactoida Vermis": 757,
        "sp:Caeruleum Sinuous Tubers": 149,
        "sp:Clypeus Lacrimam": 661,
        "sp:Clypeus Margaritus": 42,
        "sp:Clypeus Speculumi": 1424,
        "sp:Concha Aureolas": 334,
        "sp:Concha Biconcavis": 256,
        "sp:Concha Labiata": 810,
        "sp:Concha Renibus": 1872,
        "sp:Croceum Anemone": 348,
        "sp:Crystalline Shards": 75,
        "sp:Electricae Pluma": 787,
        "sp:Electricae Radialem": 116,
        "sp:Fonticulua Campestris": 1158,
        "sp:Fonticulua Digitos": 82,
        "sp:Fonticulua Fluctus": 17,
        "sp:Fonticulua Lapida": 294,
        "sp:Fonticulua Segmentatus": 86,
        "sp:Fonticulua Upupam": 165,
        "sp:Frutexa Acus": 728,
        "sp:Frutexa Collum": 44,
        "sp:Frutexa Fera": 500,
        "sp:Frutexa Flabellum": 426,
        "sp:Frutexa Flammasis": 607,
        "sp:Frutexa Metallicum": 144,
        "sp:Frutexa Sponsae": 1378,
        "sp:Fumerola Aquatis": 160,
        "sp:Fumerola Carbosis": 81,
        "sp:Fumerola Extremus": 261,
        "sp:Fumerola Nitris": 46,
        "sp:Fungoida Bullarum": 37,
        "sp:Fungoida Gelata": 1612,
        "sp:Fungoida Setisis": 1035,
        "sp:Fungoida Stabitis": 595,
        "sp:Gypseeum Brain Tree": 7,
        "sp:Lindigoticum Brain Tree": 2,
        "sp:Lindigoticum Sinuous Tubers": 42,
        "sp:Lividum Brain Tree": 99,
        "sp:Luteolum Anemone": 1478,
        "sp:Osseus Cornibus": 39,
        "sp:Osseus Discus": 1642,
        "sp:Osseus Fractus": 121,
        "sp:Osseus Pellebantus": 38,
        "sp:Osseus Pumice": 641,
        "sp:Osseus Spiralis": 413,
        "sp:Ostrinum Brain Tree": 14,
        "sp:Prasinum Sinuous Tubers": 277,
        "sp:Puniceum Brain Tree": 39,
        "sp:Recepta Conditivus": 185,
        "sp:Recepta Deltahedronix": 41,
        "sp:Recepta Umbrux": 269,
        "sp:Roseum Anemone": 281,
        "sp:Roseum Bioluminescent Anemone": 4904,
        "sp:Roseum Brain Tree": 142,
        "sp:Roseum Sinuous Tubers": 238,
        "sp:Rubeum Bioluminescent Anemone": 4852,
        "sp:Stratum Araneamus": 1418,
        "sp:Stratum Cucumisis": 166,
        "sp:Stratum Excutitus": 107,
        "sp:Stratum Frigus": 44,
        "sp:Stratum Laminamus": 44,
        "sp:Stratum Limaxus": 49,
        "sp:Stratum Paleas": 566,
        "sp:Stratum Tectonicas": 739,
        "sp:Tubus Cavas": 532,
        "sp:Tubus Compagibus": 529,
        "sp:Tubus Conifer": 186,
        "sp:Tubus Rosarium": 301,
        "sp:Tubus Sororibus": 26,
        "sp:Tussock Albata": 71,
        "sp:Tussock Capillum": 125,
        "sp:Tussock Caputus": 101,
        "sp:Tussock Catena": 255,
        "sp:Tussock Cultro": 503,
        "sp:Tussock Divisa": 91,
        "sp:Tussock Ignis": 113,
        "sp:Tussock Pennata": 37,
        "sp:Tussock Pennatis": 528,
        "sp:Tussock Propagito": 901,
        "sp:Tussock Serrati": 63,
        "sp:Tussock Stigmasis": 67,
        "sp:Tussock Triticum": 47,
        "sp:Tussock Ventusa": 66,
        "sp:Tussock Virgam": 521,
        "sp:Violaceum Sinuous Tubers": 21,
        "sp:Viride Sinuous Tubers": 26,
      },
    },
    aaA: {
      n: 282,
      hits: {
        "g:Aleoida": 13,
        "g:Anemone": 138,
        "g:Bacterium": 108,
        "g:Bark Mound": 2,
        "g:Cactoida": 10,
        "g:Clypeus": 13,
        "g:Concha": 26,
        "g:Electricae": 4,
        "g:Fonticulua": 31,
        "g:Frutexa": 29,
        "g:Fumerola": 5,
        "g:Fungoida": 25,
        "g:Osseus": 21,
        "g:Recepta": 2,
        "g:Sinuous Tuber": 6,
        "g:Stratum": 28,
        "g:Tubus": 10,
        "g:Tussock": 24,
        "sp:Albidum Sinuous Tubers": 1,
        "sp:Aleoida Arcus": 1,
        "sp:Aleoida Coronamus": 3,
        "sp:Aleoida Gravis": 5,
        "sp:Aleoida Laminiae": 3,
        "sp:Aleoida Spica": 2,
        "sp:Bacterium Acies": 2,
        "sp:Bacterium Alcyoneum": 14,
        "sp:Bacterium Aurasus": 24,
        "sp:Bacterium Bullaris": 9,
        "sp:Bacterium Cerbrus": 31,
        "sp:Bacterium Informem": 9,
        "sp:Bacterium Tela": 15,
        "sp:Bacterium Vesicula": 22,
        "sp:Bacterium Volu": 2,
        "sp:Bark Mounds": 2,
        "sp:Blatteum Bioluminescent Anemone": 53,
        "sp:Cactoida Cortexum": 2,
        "sp:Cactoida Lapis": 3,
        "sp:Cactoida Peperatis": 3,
        "sp:Cactoida Pullulanta": 2,
        "sp:Cactoida Vermis": 3,
        "sp:Caeruleum Sinuous Tubers": 2,
        "sp:Clypeus Lacrimam": 5,
        "sp:Clypeus Margaritus": 1,
        "sp:Clypeus Speculumi": 7,
        "sp:Concha Aureolas": 3,
        "sp:Concha Labiata": 12,
        "sp:Concha Renibus": 12,
        "sp:Croceum Anemone": 1,
        "sp:Electricae Pluma": 4,
        "sp:Fonticulua Campestris": 20,
        "sp:Fonticulua Digitos": 5,
        "sp:Fonticulua Lapida": 6,
        "sp:Fonticulua Upupam": 1,
        "sp:Frutexa Acus": 8,
        "sp:Frutexa Fera": 8,
        "sp:Frutexa Flabellum": 4,
        "sp:Frutexa Flammasis": 7,
        "sp:Frutexa Metallicum": 3,
        "sp:Frutexa Sponsae": 4,
        "sp:Fumerola Aquatis": 1,
        "sp:Fumerola Carbosis": 1,
        "sp:Fumerola Extremus": 2,
        "sp:Fumerola Nitris": 1,
        "sp:Fungoida Gelata": 9,
        "sp:Fungoida Setisis": 13,
        "sp:Fungoida Stabitis": 5,
        "sp:Luteolum Anemone": 12,
        "sp:Osseus Cornibus": 2,
        "sp:Osseus Discus": 7,
        "sp:Osseus Fractus": 1,
        "sp:Osseus Pellebantus": 1,
        "sp:Osseus Pumice": 5,
        "sp:Osseus Spiralis": 8,
        "sp:Prasinum Sinuous Tubers": 3,
        "sp:Recepta Umbrux": 2,
        "sp:Roseum Anemone": 2,
        "sp:Roseum Bioluminescent Anemone": 35,
        "sp:Roseum Sinuous Tubers": 3,
        "sp:Rubeum Bioluminescent Anemone": 41,
        "sp:Stratum Araneamus": 8,
        "sp:Stratum Excutitus": 4,
        "sp:Stratum Laminamus": 1,
        "sp:Stratum Paleas": 3,
        "sp:Stratum Tectonicas": 12,
        "sp:Tubus Cavas": 2,
        "sp:Tubus Compagibus": 5,
        "sp:Tubus Conifer": 4,
        "sp:Tubus Rosarium": 2,
        "sp:Tussock Capillum": 2,
        "sp:Tussock Caputus": 1,
        "sp:Tussock Cultro": 6,
        "sp:Tussock Ignis": 2,
        "sp:Tussock Pennata": 2,
        "sp:Tussock Pennatis": 9,
        "sp:Tussock Propagito": 4,
        "sp:Tussock Serrati": 1,
      },
    },
  },
  f: {
    all: {
      n: 5002,
      hits: {
        "g:Aleoida": 247,
        "g:Anemone": 1060,
        "g:Bacterium": 2428,
        "g:Bark Mound": 29,
        "g:Cactoida": 203,
        "g:Clypeus": 127,
        "g:Concha": 729,
        "g:Electricae": 398,
        "g:Fonticulua": 462,
        "g:Frutexa": 333,
        "g:Fumerola": 653,
        "g:Fungoida": 693,
        "g:Osseus": 1281,
        "g:Recepta": 91,
        "g:Sinuous Tuber": 14,
        "g:Stratum": 497,
        "g:Tubus": 133,
        "g:Tussock": 645,
        "sp:Albidum Sinuous Tubers": 2,
        "sp:Aleoida Arcus": 50,
        "sp:Aleoida Coronamus": 90,
        "sp:Aleoida Gravis": 40,
        "sp:Aleoida Laminiae": 40,
        "sp:Aleoida Spica": 40,
        "sp:Bacterium Acies": 217,
        "sp:Bacterium Alcyoneum": 190,
        "sp:Bacterium Aurasus": 301,
        "sp:Bacterium Bullaris": 378,
        "sp:Bacterium Cerbrus": 277,
        "sp:Bacterium Informem": 739,
        "sp:Bacterium Nebulus": 51,
        "sp:Bacterium Omentum": 20,
        "sp:Bacterium Scopulum": 21,
        "sp:Bacterium Tela": 288,
        "sp:Bacterium Verrata": 63,
        "sp:Bacterium Vesicula": 288,
        "sp:Bacterium Volu": 30,
        "sp:Bark Mounds": 29,
        "sp:Blatteum Bioluminescent Anemone": 243,
        "sp:Cactoida Cortexum": 60,
        "sp:Cactoida Lapis": 31,
        "sp:Cactoida Peperatis": 47,
        "sp:Cactoida Pullulanta": 31,
        "sp:Cactoida Vermis": 46,
        "sp:Clypeus Lacrimam": 77,
        "sp:Clypeus Margaritus": 2,
        "sp:Clypeus Speculumi": 48,
        "sp:Concha Aureolas": 28,
        "sp:Concha Biconcavis": 511,
        "sp:Concha Labiata": 58,
        "sp:Concha Renibus": 152,
        "sp:Croceum Anemone": 1,
        "sp:Electricae Pluma": 386,
        "sp:Electricae Radialem": 12,
        "sp:Fonticulua Campestris": 318,
        "sp:Fonticulua Digitos": 9,
        "sp:Fonticulua Fluctus": 2,
        "sp:Fonticulua Lapida": 81,
        "sp:Fonticulua Segmentatus": 24,
        "sp:Fonticulua Upupam": 39,
        "sp:Frutexa Acus": 85,
        "sp:Frutexa Collum": 11,
        "sp:Frutexa Fera": 67,
        "sp:Frutexa Flabellum": 62,
        "sp:Frutexa Flammasis": 80,
        "sp:Frutexa Metallicum": 4,
        "sp:Frutexa Sponsae": 54,
        "sp:Fumerola Aquatis": 187,
        "sp:Fumerola Carbosis": 52,
        "sp:Fumerola Extremus": 404,
        "sp:Fumerola Nitris": 23,
        "sp:Fungoida Bullarum": 43,
        "sp:Fungoida Gelata": 183,
        "sp:Fungoida Setisis": 428,
        "sp:Fungoida Stabitis": 80,
        "sp:Luteolum Anemone": 1,
        "sp:Osseus Cornibus": 11,
        "sp:Osseus Discus": 239,
        "sp:Osseus Fractus": 13,
        "sp:Osseus Pellebantus": 11,
        "sp:Osseus Pumice": 1045,
        "sp:Osseus Spiralis": 41,
        "sp:Prasinum Bioluminescent Anemone": 743,
        "sp:Prasinum Sinuous Tubers": 9,
        "sp:Puniceum Anemone": 4,
        "sp:Recepta Conditivus": 21,
        "sp:Recepta Deltahedronix": 29,
        "sp:Recepta Umbrux": 41,
        "sp:Roseum Bioluminescent Anemone": 30,
        "sp:Roseum Sinuous Tubers": 6,
        "sp:Rubeum Bioluminescent Anemone": 44,
        "sp:Stratum Araneamus": 83,
        "sp:Stratum Cucumisis": 89,
        "sp:Stratum Excutitus": 60,
        "sp:Stratum Frigus": 19,
        "sp:Stratum Laminamus": 20,
        "sp:Stratum Limaxus": 17,
        "sp:Stratum Paleas": 204,
        "sp:Stratum Tectonicas": 35,
        "sp:Tubus Cavas": 41,
        "sp:Tubus Compagibus": 45,
        "sp:Tubus Conifer": 27,
        "sp:Tubus Rosarium": 33,
        "sp:Tubus Sororibus": 2,
        "sp:Tussock Albata": 8,
        "sp:Tussock Capillum": 158,
        "sp:Tussock Caputus": 14,
        "sp:Tussock Catena": 24,
        "sp:Tussock Cultro": 91,
        "sp:Tussock Divisa": 21,
        "sp:Tussock Ignis": 7,
        "sp:Tussock Pennata": 2,
        "sp:Tussock Pennatis": 111,
        "sp:Tussock Propagito": 143,
        "sp:Tussock Serrati": 4,
        "sp:Tussock Stigmasis": 45,
        "sp:Tussock Triticum": 11,
        "sp:Tussock Ventusa": 1,
        "sp:Tussock Virgam": 47,
      },
    },
    aaA: {
      n: 277,
      hits: {
        "g:Aleoida": 13,
        "g:Anemone": 35,
        "g:Bacterium": 184,
        "g:Cactoida": 19,
        "g:Clypeus": 9,
        "g:Concha": 42,
        "g:Electricae": 28,
        "g:Fonticulua": 23,
        "g:Frutexa": 24,
        "g:Fumerola": 31,
        "g:Fungoida": 46,
        "g:Osseus": 85,
        "g:Recepta": 7,
        "g:Stratum": 39,
        "g:Tubus": 10,
        "g:Tussock": 46,
        "sp:Aleoida Arcus": 3,
        "sp:Aleoida Coronamus": 6,
        "sp:Aleoida Gravis": 1,
        "sp:Aleoida Laminiae": 3,
        "sp:Aleoida Spica": 1,
        "sp:Bacterium Acies": 9,
        "sp:Bacterium Alcyoneum": 15,
        "sp:Bacterium Aurasus": 24,
        "sp:Bacterium Bullaris": 40,
        "sp:Bacterium Cerbrus": 30,
        "sp:Bacterium Informem": 42,
        "sp:Bacterium Nebulus": 3,
        "sp:Bacterium Omentum": 2,
        "sp:Bacterium Scopulum": 1,
        "sp:Bacterium Tela": 22,
        "sp:Bacterium Verrata": 4,
        "sp:Bacterium Vesicula": 25,
        "sp:Bacterium Volu": 3,
        "sp:Blatteum Bioluminescent Anemone": 8,
        "sp:Cactoida Cortexum": 2,
        "sp:Cactoida Lapis": 1,
        "sp:Cactoida Peperatis": 5,
        "sp:Cactoida Pullulanta": 5,
        "sp:Cactoida Vermis": 6,
        "sp:Clypeus Lacrimam": 5,
        "sp:Clypeus Speculumi": 4,
        "sp:Concha Aureolas": 2,
        "sp:Concha Biconcavis": 26,
        "sp:Concha Labiata": 6,
        "sp:Concha Renibus": 9,
        "sp:Electricae Pluma": 28,
        "sp:Fonticulua Campestris": 21,
        "sp:Fonticulua Lapida": 1,
        "sp:Fonticulua Upupam": 1,
        "sp:Frutexa Acus": 4,
        "sp:Frutexa Collum": 2,
        "sp:Frutexa Fera": 4,
        "sp:Frutexa Flabellum": 4,
        "sp:Frutexa Flammasis": 7,
        "sp:Frutexa Sponsae": 6,
        "sp:Fumerola Aquatis": 12,
        "sp:Fumerola Carbosis": 3,
        "sp:Fumerola Extremus": 18,
        "sp:Fungoida Bullarum": 1,
        "sp:Fungoida Gelata": 9,
        "sp:Fungoida Setisis": 36,
        "sp:Fungoida Stabitis": 3,
        "sp:Osseus Cornibus": 1,
        "sp:Osseus Discus": 10,
        "sp:Osseus Fractus": 2,
        "sp:Osseus Pumice": 73,
        "sp:Osseus Spiralis": 4,
        "sp:Prasinum Bioluminescent Anemone": 22,
        "sp:Recepta Conditivus": 2,
        "sp:Recepta Deltahedronix": 1,
        "sp:Recepta Umbrux": 4,
        "sp:Roseum Bioluminescent Anemone": 1,
        "sp:Rubeum Bioluminescent Anemone": 4,
        "sp:Stratum Araneamus": 10,
        "sp:Stratum Cucumisis": 9,
        "sp:Stratum Excutitus": 3,
        "sp:Stratum Frigus": 4,
        "sp:Stratum Limaxus": 1,
        "sp:Stratum Paleas": 11,
        "sp:Stratum Tectonicas": 3,
        "sp:Tubus Cavas": 3,
        "sp:Tubus Compagibus": 2,
        "sp:Tubus Conifer": 2,
        "sp:Tubus Rosarium": 4,
        "sp:Tussock Albata": 1,
        "sp:Tussock Capillum": 9,
        "sp:Tussock Caputus": 1,
        "sp:Tussock Catena": 1,
        "sp:Tussock Cultro": 8,
        "sp:Tussock Divisa": 2,
        "sp:Tussock Pennata": 1,
        "sp:Tussock Pennatis": 5,
        "sp:Tussock Propagito": 10,
        "sp:Tussock Stigmasis": 5,
        "sp:Tussock Triticum": 2,
        "sp:Tussock Virgam": 5,
      },
    },
  },
  g: {
    all: {
      n: 4659,
      hits: {
        "g:Aleoida": 200,
        "g:Anemone": 2191,
        "g:Bacterium": 1624,
        "g:Bark Mound": 9,
        "g:Cactoida": 155,
        "g:Clypeus": 76,
        "g:Concha": 338,
        "g:Electricae": 135,
        "g:Fonticulua": 181,
        "g:Frutexa": 219,
        "g:Fumerola": 286,
        "g:Fungoida": 396,
        "g:Osseus": 643,
        "g:Recepta": 85,
        "g:Sinuous Tuber": 7,
        "g:Stratum": 666,
        "g:Tubus": 77,
        "g:Tussock": 458,
        "sp:Aleoida Arcus": 38,
        "sp:Aleoida Coronamus": 59,
        "sp:Aleoida Gravis": 41,
        "sp:Aleoida Laminiae": 34,
        "sp:Aleoida Spica": 35,
        "sp:Bacterium Acies": 143,
        "sp:Bacterium Alcyoneum": 149,
        "sp:Bacterium Aurasus": 268,
        "sp:Bacterium Bullaris": 192,
        "sp:Bacterium Cerbrus": 342,
        "sp:Bacterium Informem": 533,
        "sp:Bacterium Nebulus": 22,
        "sp:Bacterium Omentum": 15,
        "sp:Bacterium Scopulum": 14,
        "sp:Bacterium Tela": 213,
        "sp:Bacterium Verrata": 13,
        "sp:Bacterium Vesicula": 117,
        "sp:Bacterium Volu": 26,
        "sp:Bark Mounds": 9,
        "sp:Blatteum Bioluminescent Anemone": 238,
        "sp:Cactoida Cortexum": 52,
        "sp:Cactoida Lapis": 43,
        "sp:Cactoida Peperatis": 38,
        "sp:Cactoida Pullulanta": 21,
        "sp:Cactoida Vermis": 11,
        "sp:Caeruleum Sinuous Tubers": 2,
        "sp:Clypeus Lacrimam": 65,
        "sp:Clypeus Margaritus": 1,
        "sp:Clypeus Speculumi": 10,
        "sp:Concha Aureolas": 4,
        "sp:Concha Biconcavis": 223,
        "sp:Concha Labiata": 23,
        "sp:Concha Renibus": 92,
        "sp:Croceum Anemone": 2,
        "sp:Electricae Pluma": 132,
        "sp:Electricae Radialem": 3,
        "sp:Fonticulua Campestris": 115,
        "sp:Fonticulua Digitos": 3,
        "sp:Fonticulua Fluctus": 1,
        "sp:Fonticulua Lapida": 36,
        "sp:Fonticulua Segmentatus": 13,
        "sp:Fonticulua Upupam": 21,
        "sp:Frutexa Acus": 68,
        "sp:Frutexa Collum": 18,
        "sp:Frutexa Fera": 25,
        "sp:Frutexa Flabellum": 44,
        "sp:Frutexa Flammasis": 66,
        "sp:Frutexa Metallicum": 1,
        "sp:Frutexa Sponsae": 12,
        "sp:Fumerola Aquatis": 54,
        "sp:Fumerola Carbosis": 21,
        "sp:Fumerola Extremus": 213,
        "sp:Fumerola Nitris": 7,
        "sp:Fungoida Bullarum": 21,
        "sp:Fungoida Gelata": 110,
        "sp:Fungoida Setisis": 234,
        "sp:Fungoida Stabitis": 62,
        "sp:Luteolum Anemone": 3,
        "sp:Osseus Cornibus": 7,
        "sp:Osseus Discus": 117,
        "sp:Osseus Fractus": 20,
        "sp:Osseus Pellebantus": 5,
        "sp:Osseus Pumice": 491,
        "sp:Osseus Spiralis": 38,
        "sp:Prasinum Bioluminescent Anemone": 1880,
        "sp:Prasinum Sinuous Tubers": 4,
        "sp:Puniceum Anemone": 63,
        "sp:Recepta Conditivus": 20,
        "sp:Recepta Deltahedronix": 19,
        "sp:Recepta Umbrux": 46,
        "sp:Roseum Anemone": 4,
        "sp:Roseum Bioluminescent Anemone": 21,
        "sp:Roseum Sinuous Tubers": 3,
        "sp:Rubeum Bioluminescent Anemone": 17,
        "sp:Stratum Araneamus": 55,
        "sp:Stratum Cucumisis": 198,
        "sp:Stratum Excutitus": 71,
        "sp:Stratum Frigus": 36,
        "sp:Stratum Laminamus": 22,
        "sp:Stratum Limaxus": 38,
        "sp:Stratum Paleas": 306,
        "sp:Stratum Tectonicas": 14,
        "sp:Tubus Cavas": 29,
        "sp:Tubus Compagibus": 31,
        "sp:Tubus Conifer": 13,
        "sp:Tubus Rosarium": 14,
        "sp:Tussock Albata": 13,
        "sp:Tussock Capillum": 68,
        "sp:Tussock Caputus": 17,
        "sp:Tussock Catena": 31,
        "sp:Tussock Cultro": 92,
        "sp:Tussock Divisa": 5,
        "sp:Tussock Ignis": 6,
        "sp:Tussock Pennatis": 74,
        "sp:Tussock Propagito": 119,
        "sp:Tussock Serrati": 3,
        "sp:Tussock Stigmasis": 50,
        "sp:Tussock Triticum": 6,
        "sp:Tussock Ventusa": 2,
        "sp:Tussock Virgam": 14,
      },
    },
    aaA: {
      n: 1275,
      hits: {
        "g:Aleoida": 61,
        "g:Anemone": 401,
        "g:Bacterium": 590,
        "g:Cactoida": 56,
        "g:Clypeus": 28,
        "g:Concha": 103,
        "g:Electricae": 40,
        "g:Fonticulua": 54,
        "g:Frutexa": 68,
        "g:Fumerola": 99,
        "g:Fungoida": 119,
        "g:Osseus": 229,
        "g:Recepta": 31,
        "g:Sinuous Tuber": 1,
        "g:Stratum": 239,
        "g:Tubus": 31,
        "g:Tussock": 160,
        "sp:Aleoida Arcus": 13,
        "sp:Aleoida Coronamus": 13,
        "sp:Aleoida Gravis": 15,
        "sp:Aleoida Laminiae": 12,
        "sp:Aleoida Spica": 11,
        "sp:Bacterium Acies": 35,
        "sp:Bacterium Alcyoneum": 46,
        "sp:Bacterium Aurasus": 93,
        "sp:Bacterium Bullaris": 67,
        "sp:Bacterium Cerbrus": 113,
        "sp:Bacterium Informem": 274,
        "sp:Bacterium Nebulus": 7,
        "sp:Bacterium Omentum": 6,
        "sp:Bacterium Scopulum": 2,
        "sp:Bacterium Tela": 64,
        "sp:Bacterium Verrata": 5,
        "sp:Bacterium Vesicula": 34,
        "sp:Bacterium Volu": 7,
        "sp:Blatteum Bioluminescent Anemone": 51,
        "sp:Cactoida Cortexum": 27,
        "sp:Cactoida Lapis": 9,
        "sp:Cactoida Peperatis": 13,
        "sp:Cactoida Pullulanta": 7,
        "sp:Cactoida Vermis": 2,
        "sp:Caeruleum Sinuous Tubers": 1,
        "sp:Clypeus Lacrimam": 26,
        "sp:Clypeus Speculumi": 2,
        "sp:Concha Biconcavis": 73,
        "sp:Concha Labiata": 2,
        "sp:Concha Renibus": 29,
        "sp:Electricae Pluma": 38,
        "sp:Electricae Radialem": 2,
        "sp:Fonticulua Campestris": 32,
        "sp:Fonticulua Digitos": 1,
        "sp:Fonticulua Lapida": 12,
        "sp:Fonticulua Segmentatus": 4,
        "sp:Fonticulua Upupam": 8,
        "sp:Frutexa Acus": 27,
        "sp:Frutexa Collum": 4,
        "sp:Frutexa Fera": 4,
        "sp:Frutexa Flabellum": 12,
        "sp:Frutexa Flammasis": 22,
        "sp:Frutexa Sponsae": 4,
        "sp:Fumerola Aquatis": 18,
        "sp:Fumerola Carbosis": 4,
        "sp:Fumerola Extremus": 77,
        "sp:Fumerola Nitris": 3,
        "sp:Fungoida Bullarum": 6,
        "sp:Fungoida Gelata": 27,
        "sp:Fungoida Setisis": 73,
        "sp:Fungoida Stabitis": 22,
        "sp:Osseus Cornibus": 2,
        "sp:Osseus Discus": 37,
        "sp:Osseus Fractus": 4,
        "sp:Osseus Pellebantus": 1,
        "sp:Osseus Pumice": 187,
        "sp:Osseus Spiralis": 9,
        "sp:Prasinum Bioluminescent Anemone": 339,
        "sp:Prasinum Sinuous Tubers": 1,
        "sp:Puniceum Anemone": 8,
        "sp:Recepta Conditivus": 6,
        "sp:Recepta Deltahedronix": 6,
        "sp:Recepta Umbrux": 19,
        "sp:Roseum Anemone": 1,
        "sp:Roseum Bioluminescent Anemone": 7,
        "sp:Roseum Sinuous Tubers": 1,
        "sp:Rubeum Bioluminescent Anemone": 2,
        "sp:Stratum Araneamus": 17,
        "sp:Stratum Cucumisis": 89,
        "sp:Stratum Excutitus": 31,
        "sp:Stratum Frigus": 11,
        "sp:Stratum Laminamus": 6,
        "sp:Stratum Limaxus": 9,
        "sp:Stratum Paleas": 104,
        "sp:Stratum Tectonicas": 4,
        "sp:Tubus Cavas": 13,
        "sp:Tubus Compagibus": 12,
        "sp:Tubus Conifer": 4,
        "sp:Tubus Rosarium": 8,
        "sp:Tussock Albata": 6,
        "sp:Tussock Capillum": 25,
        "sp:Tussock Caputus": 5,
        "sp:Tussock Catena": 9,
        "sp:Tussock Cultro": 36,
        "sp:Tussock Ignis": 3,
        "sp:Tussock Pennatis": 15,
        "sp:Tussock Propagito": 42,
        "sp:Tussock Serrati": 3,
        "sp:Tussock Stigmasis": 21,
        "sp:Tussock Triticum": 4,
        "sp:Tussock Ventusa": 2,
        "sp:Tussock Virgam": 3,
      },
    },
  },
  h: {
    all: {
      n: 1446,
      hits: {
        "g:Aleoida": 65,
        "g:Anemone": 239,
        "g:Bacterium": 775,
        "g:Bark Mound": 5,
        "g:Brain Tree": 2,
        "g:Cactoida": 39,
        "g:Clypeus": 25,
        "g:Concha": 100,
        "g:Electricae": 45,
        "g:Fonticulua": 45,
        "g:Frutexa": 76,
        "g:Fumerola": 135,
        "g:Fungoida": 129,
        "g:Osseus": 211,
        "g:Recepta": 33,
        "g:Sinuous Tuber": 10,
        "g:Stratum": 465,
        "g:Tubus": 18,
        "g:Tussock": 171,
        "sp:Albidum Sinuous Tubers": 1,
        "sp:Aleoida Arcus": 7,
        "sp:Aleoida Coronamus": 15,
        "sp:Aleoida Gravis": 15,
        "sp:Aleoida Laminiae": 16,
        "sp:Aleoida Spica": 13,
        "sp:Bacterium Acies": 35,
        "sp:Bacterium Alcyoneum": 68,
        "sp:Bacterium Aurasus": 130,
        "sp:Bacterium Bullaris": 74,
        "sp:Bacterium Cerbrus": 272,
        "sp:Bacterium Informem": 174,
        "sp:Bacterium Nebulus": 3,
        "sp:Bacterium Omentum": 4,
        "sp:Bacterium Scopulum": 4,
        "sp:Bacterium Tela": 142,
        "sp:Bacterium Verrata": 21,
        "sp:Bacterium Vesicula": 35,
        "sp:Bacterium Volu": 17,
        "sp:Bark Mounds": 5,
        "sp:Blatteum Bioluminescent Anemone": 11,
        "sp:Blatteum Sinuous Tubers": 1,
        "sp:Cactoida Cortexum": 9,
        "sp:Cactoida Lapis": 12,
        "sp:Cactoida Peperatis": 13,
        "sp:Cactoida Pullulanta": 5,
        "sp:Caeruleum Sinuous Tubers": 1,
        "sp:Clypeus Lacrimam": 23,
        "sp:Clypeus Speculumi": 2,
        "sp:Concha Biconcavis": 70,
        "sp:Concha Labiata": 5,
        "sp:Concha Renibus": 25,
        "sp:Electricae Pluma": 42,
        "sp:Electricae Radialem": 3,
        "sp:Fonticulua Campestris": 29,
        "sp:Fonticulua Fluctus": 1,
        "sp:Fonticulua Lapida": 7,
        "sp:Fonticulua Segmentatus": 4,
        "sp:Fonticulua Upupam": 4,
        "sp:Frutexa Acus": 14,
        "sp:Frutexa Collum": 11,
        "sp:Frutexa Fera": 11,
        "sp:Frutexa Flabellum": 19,
        "sp:Frutexa Flammasis": 21,
        "sp:Frutexa Metallicum": 1,
        "sp:Frutexa Sponsae": 2,
        "sp:Fumerola Aquatis": 38,
        "sp:Fumerola Carbosis": 12,
        "sp:Fumerola Extremus": 90,
        "sp:Fumerola Nitris": 3,
        "sp:Fungoida Bullarum": 8,
        "sp:Fungoida Gelata": 24,
        "sp:Fungoida Setisis": 94,
        "sp:Fungoida Stabitis": 12,
        "sp:Gypseeum Brain Tree": 1,
        "sp:Osseus Cornibus": 8,
        "sp:Osseus Discus": 36,
        "sp:Osseus Fractus": 2,
        "sp:Osseus Pellebantus": 1,
        "sp:Osseus Pumice": 161,
        "sp:Osseus Spiralis": 13,
        "sp:Prasinum Bioluminescent Anemone": 203,
        "sp:Prasinum Sinuous Tubers": 4,
        "sp:Puniceum Anemone": 16,
        "sp:Puniceum Brain Tree": 1,
        "sp:Recepta Conditivus": 9,
        "sp:Recepta Deltahedronix": 6,
        "sp:Recepta Umbrux": 18,
        "sp:Roseum Bioluminescent Anemone": 11,
        "sp:Roseum Brain Tree": 1,
        "sp:Roseum Sinuous Tubers": 6,
        "sp:Rubeum Bioluminescent Anemone": 2,
        "sp:Stratum Araneamus": 26,
        "sp:Stratum Cucumisis": 183,
        "sp:Stratum Excutitus": 41,
        "sp:Stratum Frigus": 31,
        "sp:Stratum Laminamus": 18,
        "sp:Stratum Limaxus": 14,
        "sp:Stratum Paleas": 205,
        "sp:Stratum Tectonicas": 8,
        "sp:Tubus Cavas": 4,
        "sp:Tubus Compagibus": 4,
        "sp:Tubus Conifer": 6,
        "sp:Tubus Rosarium": 6,
        "sp:Tussock Albata": 5,
        "sp:Tussock Capillum": 33,
        "sp:Tussock Caputus": 4,
        "sp:Tussock Catena": 11,
        "sp:Tussock Cultro": 39,
        "sp:Tussock Divisa": 10,
        "sp:Tussock Ignis": 2,
        "sp:Tussock Pennatis": 22,
        "sp:Tussock Propagito": 23,
        "sp:Tussock Serrati": 2,
        "sp:Tussock Stigmasis": 23,
        "sp:Tussock Triticum": 2,
        "sp:Tussock Ventusa": 1,
        "sp:Tussock Virgam": 2,
      },
    },
    aaA: {
      n: 1446,
      hits: {
        "g:Aleoida": 65,
        "g:Anemone": 239,
        "g:Bacterium": 775,
        "g:Bark Mound": 5,
        "g:Brain Tree": 2,
        "g:Cactoida": 39,
        "g:Clypeus": 25,
        "g:Concha": 100,
        "g:Electricae": 45,
        "g:Fonticulua": 45,
        "g:Frutexa": 76,
        "g:Fumerola": 135,
        "g:Fungoida": 129,
        "g:Osseus": 211,
        "g:Recepta": 33,
        "g:Sinuous Tuber": 10,
        "g:Stratum": 465,
        "g:Tubus": 18,
        "g:Tussock": 171,
        "sp:Albidum Sinuous Tubers": 1,
        "sp:Aleoida Arcus": 7,
        "sp:Aleoida Coronamus": 15,
        "sp:Aleoida Gravis": 15,
        "sp:Aleoida Laminiae": 16,
        "sp:Aleoida Spica": 13,
        "sp:Bacterium Acies": 35,
        "sp:Bacterium Alcyoneum": 68,
        "sp:Bacterium Aurasus": 130,
        "sp:Bacterium Bullaris": 74,
        "sp:Bacterium Cerbrus": 272,
        "sp:Bacterium Informem": 174,
        "sp:Bacterium Nebulus": 3,
        "sp:Bacterium Omentum": 4,
        "sp:Bacterium Scopulum": 4,
        "sp:Bacterium Tela": 142,
        "sp:Bacterium Verrata": 21,
        "sp:Bacterium Vesicula": 35,
        "sp:Bacterium Volu": 17,
        "sp:Bark Mounds": 5,
        "sp:Blatteum Bioluminescent Anemone": 11,
        "sp:Blatteum Sinuous Tubers": 1,
        "sp:Cactoida Cortexum": 9,
        "sp:Cactoida Lapis": 12,
        "sp:Cactoida Peperatis": 13,
        "sp:Cactoida Pullulanta": 5,
        "sp:Caeruleum Sinuous Tubers": 1,
        "sp:Clypeus Lacrimam": 23,
        "sp:Clypeus Speculumi": 2,
        "sp:Concha Biconcavis": 70,
        "sp:Concha Labiata": 5,
        "sp:Concha Renibus": 25,
        "sp:Electricae Pluma": 42,
        "sp:Electricae Radialem": 3,
        "sp:Fonticulua Campestris": 29,
        "sp:Fonticulua Fluctus": 1,
        "sp:Fonticulua Lapida": 7,
        "sp:Fonticulua Segmentatus": 4,
        "sp:Fonticulua Upupam": 4,
        "sp:Frutexa Acus": 14,
        "sp:Frutexa Collum": 11,
        "sp:Frutexa Fera": 11,
        "sp:Frutexa Flabellum": 19,
        "sp:Frutexa Flammasis": 21,
        "sp:Frutexa Metallicum": 1,
        "sp:Frutexa Sponsae": 2,
        "sp:Fumerola Aquatis": 38,
        "sp:Fumerola Carbosis": 12,
        "sp:Fumerola Extremus": 90,
        "sp:Fumerola Nitris": 3,
        "sp:Fungoida Bullarum": 8,
        "sp:Fungoida Gelata": 24,
        "sp:Fungoida Setisis": 94,
        "sp:Fungoida Stabitis": 12,
        "sp:Gypseeum Brain Tree": 1,
        "sp:Osseus Cornibus": 8,
        "sp:Osseus Discus": 36,
        "sp:Osseus Fractus": 2,
        "sp:Osseus Pellebantus": 1,
        "sp:Osseus Pumice": 161,
        "sp:Osseus Spiralis": 13,
        "sp:Prasinum Bioluminescent Anemone": 203,
        "sp:Prasinum Sinuous Tubers": 4,
        "sp:Puniceum Anemone": 16,
        "sp:Puniceum Brain Tree": 1,
        "sp:Recepta Conditivus": 9,
        "sp:Recepta Deltahedronix": 6,
        "sp:Recepta Umbrux": 18,
        "sp:Roseum Bioluminescent Anemone": 11,
        "sp:Roseum Brain Tree": 1,
        "sp:Roseum Sinuous Tubers": 6,
        "sp:Rubeum Bioluminescent Anemone": 2,
        "sp:Stratum Araneamus": 26,
        "sp:Stratum Cucumisis": 183,
        "sp:Stratum Excutitus": 41,
        "sp:Stratum Frigus": 31,
        "sp:Stratum Laminamus": 18,
        "sp:Stratum Limaxus": 14,
        "sp:Stratum Paleas": 205,
        "sp:Stratum Tectonicas": 8,
        "sp:Tubus Cavas": 4,
        "sp:Tubus Compagibus": 4,
        "sp:Tubus Conifer": 6,
        "sp:Tubus Rosarium": 6,
        "sp:Tussock Albata": 5,
        "sp:Tussock Capillum": 33,
        "sp:Tussock Caputus": 4,
        "sp:Tussock Catena": 11,
        "sp:Tussock Cultro": 39,
        "sp:Tussock Divisa": 10,
        "sp:Tussock Ignis": 2,
        "sp:Tussock Pennatis": 22,
        "sp:Tussock Propagito": 23,
        "sp:Tussock Serrati": 2,
        "sp:Tussock Stigmasis": 23,
        "sp:Tussock Triticum": 2,
        "sp:Tussock Ventusa": 1,
        "sp:Tussock Virgam": 2,
      },
    },
  },
};

export const BOXEL_BIO_GOLDEN: readonly (readonly [string, string, number, number, number, number])[] = [
  ["sp:Electricae Radialem", "d", 16641, 1057, 69, 0.00264],
  ["sp:Electricae Radialem", "d", 33026, 719, 42, 0.00268],
  ["sp:Electricae Radialem", "d", 16512, 462, 27, 0.0027],
  ["sp:Electricae Radialem", "d", 16513, 1476, 80, 0.00262],
  ["sp:Bark Mounds", "d", 16513, 1476, 470, 0.0171],
  ["g:Bark Mound", "d", 16513, 1476, 470, 0.0171],
  ["sp:Electricae Radialem", "d", 32897, 1099, 54, 0.00266],
  ["sp:Electricae Radialem", "d", 16642, 802, 39, 0.00268],
  ["sp:Bark Mounds", "d", 16514, 1081, 332, 0.0173],
  ["g:Bark Mound", "d", 16514, 1081, 332, 0.0173],
  ["sp:Bark Mounds", "d", 32897, 1099, 335, 0.0173],
  ["g:Bark Mound", "d", 32897, 1099, 335, 0.0173],
  ["sp:Bark Mounds", "d", 16641, 1057, 285, 0.01738],
  ["g:Bark Mound", "d", 16641, 1057, 285, 0.01738],
  ["sp:Electricae Radialem", "d", 16514, 1081, 44, 0.00267],
  ["sp:Electricae Radialem", "d", 33025, 782, 32, 0.00269],
  ["sp:Bark Mounds", "d", 33025, 782, 193, 0.01751],
  ["g:Bark Mound", "d", 33025, 782, 193, 0.01751],
  ["sp:Bark Mounds", "d", 32898, 869, 203, 0.0175],
  ["g:Bark Mound", "d", 32898, 869, 203, 0.0175],
  ["sp:Electricae Radialem", "d", 32898, 869, 31, 0.00269],
  ["sp:Bark Mounds", "d", 16642, 802, 181, 0.01753],
  ["g:Bark Mound", "d", 16642, 802, 181, 0.01753],
  ["sp:Bark Mounds", "d", 33026, 719, 153, 0.01757],
  ["g:Bark Mound", "d", 33026, 719, 153, 0.01757],
  ["sp:Bark Mounds", "d", 129, 612, 112, 0.01763],
  ["g:Bark Mound", "d", 129, 612, 112, 0.01763],
  ["sp:Bark Mounds", "d", 16512, 462, 84, 0.01767],
  ["g:Bark Mound", "d", 16512, 462, 84, 0.01767],
  ["sp:Bark Mounds", "d", 16640, 340, 59, 0.01771],
  ["g:Bark Mound", "d", 16640, 340, 59, 0.01771],
  ["sp:Bark Mounds", "d", 130, 428, 68, 0.0177],
  ["g:Bark Mound", "d", 130, 428, 68, 0.0177],
  ["sp:Bark Mounds", "d", 257, 341, 44, 0.01773],
  ["g:Bark Mound", "d", 257, 341, 44, 0.01773],
  ["sp:Bacterium Acies", "d", 16385, 1681, 78, 0.00757],
  ["sp:Bark Mounds", "d", 16515, 330, 34, 0.01775],
  ["g:Bark Mound", "d", 16515, 330, 34, 0.01775],
  ["sp:Bark Mounds", "d", 16386, 562, 56, 0.01772],
  ["g:Bark Mound", "d", 16386, 562, 56, 0.01772],
  ["sp:Bark Mounds", "d", 32896, 355, 34, 0.01775],
  ["g:Bark Mound", "d", 32896, 355, 34, 0.01775],
  ["sp:Bark Mounds", "d", 32770, 473, 45, 0.01773],
  ["g:Bark Mound", "d", 32770, 473, 45, 0.01773],
  ["g:Electricae", "d", 16641, 1057, 77, 0.01433],
  ["sp:Bark Mounds", "d", 32769, 478, 40, 0.01774],
  ["g:Bark Mound", "d", 32769, 478, 40, 0.01774],
  ["sp:Electricae Radialem", "d", 16385, 1681, 21, 0.00271],
  ["g:Electricae", "d", 16512, 462, 30, 0.01439],
  ["g:Electricae", "d", 16640, 340, 22, 0.0144],
  ["g:Electricae", "d", 33026, 719, 46, 0.01437],
  ["sp:Bark Mounds", "d", 49409, 317, 25, 0.01776],
  ["g:Bark Mound", "d", 49409, 317, 25, 0.01776],
  ["g:Electricae", "d", 257, 341, 20, 0.0144],
  ["g:Electricae", "d", 16513, 1476, 84, 0.01433],
  ["g:Electricae", "d", 32897, 1099, 57, 0.01436],
  ["g:Electricae", "d", 33025, 782, 40, 0.01438],
  ["g:Electricae", "d", 130, 428, 21, 0.0144],
  ["g:Electricae", "d", 16514, 1081, 49, 0.01437],
  ["sp:Frutexa Fera", "d", 18305, 420, 31, 0.02443],
  ["sp:Bacterium Informem", "g", 0, 1275, 274, 0.07654],
  ["g:Electricae", "d", 32898, 869, 33, 0.01439],
  ["sp:Roseum Brain Tree", "d", 16513, 1476, 41, 0.01087],
  ["sp:Tussock Pennatis", "d", 245765, 397, 31, 0.03239],
  ["sp:Tussock Pennatis", "d", 1, 697, 51, 0.03237],
  ["g:Brain Tree", "d", 16513, 1476, 52, 0.016],
  ["sp:Stratum Tectonicas", "d", 180229, 362, 82, 0.13092],
  ["sp:Fonticulua Campestris", "d", 16641, 1057, 94, 0.05186],
  ["g:Fonticulua", "d", 16641, 1057, 125, 0.07243],
  ["sp:Tussock Cultro", "d", 16641, 1057, 105, 0.06103],
  ["sp:Fonticulua Campestris", "d", 16513, 1476, 123, 0.05185],
  ["g:Bacterium", "g", 0, 1275, 590, 0.30556],
  ["g:Anemone", "g", 16512, 369, 251, 0.45221],
];
