/**
 * Builds `tests/fixtures/match-golden.json` from the local journal merge cache.
 *
 * The probe needs this commander's journal and so cannot run anywhere else. The fixture is the part
 * that travels: twenty real scans, checked into the repository, with the candidate list each one
 * produces today. `tests/matchGolden.test.ts` re-matches them on every run, so any change to a gate,
 * a band or the matcher shows up as an explicit diff instead of as a number nobody re-ran.
 *
 * Selection covers every atmosphere type in the truth set and both temperature clusters of the
 * bimodal species, which is where the interesting failures live.
 *
 *   npx tsx scripts/gen-match-fixture.ts
 *
 * Re-run it deliberately when a change is *meant* to move predictions, and review the diff.
 */
import { readFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import v8 from "node:v8";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadSpeciesDatabaseFromTree } from "../src/server/speciesTreeLoader.js";
import { matchDatabaseToScan } from "../src/server/matchSpecies.js";
import { decodeJournalMergeCache } from "../src/server/journalMergeCacheEncoding.js";
import { collectResolvedOrganicLockSpeciesIds } from "../src/server/organicLocks.js";
import { resolveJournalMergeCacheRoot } from "../src/server/paths.js";
import type { BodyExoState, PlanetScan } from "../src/shared/types.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const db = loadSpeciesDatabaseFromTree(root);

const payloadPath = path.join(resolveJournalMergeCacheRoot(), "journal-merge.payload.v8gz");
if (!existsSync(payloadPath)) {
  console.error(`No journal merge cache at ${payloadPath}. Run the app once to build it.`);
  process.exit(1);
}
const raw = readFileSync(payloadPath);
const doc =
  raw[0] === 0x1f && raw[1] === 0x8b ? v8.deserialize(gunzipSync(raw)) : JSON.parse(raw.toString("utf8"));
const payload = decodeJournalMergeCache(doc);
if (!payload) {
  console.error("Cache is not in the current encoding.");
  process.exit(1);
}

const bodies: BodyExoState[] = payload.bodies.map(([, b]) => b);

/** Only the fields the matcher reads, so the fixture stays small and its inputs are obvious. */
const SCAN_FIELDS = [
  "PlanetClass",
  "AtmosphereType",
  "Atmosphere",
  "SurfaceTemperature",
  "SurfaceGravity",
  "SurfacePressure",
  "Volcanism",
  "Landable",
  "MassEM",
  "Radius",
  "SemiMajorAxis",
  "Eccentricity",
  "TidalLock",
  "TerraformState",
  "WasDiscovered",
  "WasMapped",
] as const;

function trimScan(scan: PlanetScan): Record<string, unknown> {
  const src = scan as unknown as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const k of SCAN_FIELDS) {
    if (src[k] !== undefined && src[k] !== null) out[k] = src[k];
  }
  return out;
}

interface Candidate {
  bodyName: string;
  scan: PlanetScan;
  truth: string[];
  atmo: string;
  temp: number;
}

const pool: Candidate[] = [];
for (const b of bodies) {
  const truth = collectResolvedOrganicLockSpeciesIds(b.organicGenusLocks, db);
  if (!truth.length || !b.scan?.PlanetClass?.trim()) continue;
  pool.push({
    bodyName: b.bodyName,
    scan: b.scan,
    truth: [...truth].sort(),
    atmo: (b.scan.AtmosphereType ?? "none").trim() || "none",
    temp: b.scan.SurfaceTemperature ?? 0,
  });
}
pool.sort((a, b) => a.bodyName.localeCompare(b.bodyName));

// One cold and one hot body per atmosphere type, up to twenty, so both clusters of the bimodal
// species are represented rather than whichever the sort happened to reach first.
const picked: Candidate[] = [];
const byAtmo = new Map<string, Candidate[]>();
for (const c of pool) {
  const list = byAtmo.get(c.atmo) ?? [];
  list.push(c);
  byAtmo.set(c.atmo, list);
}
for (const [, list] of [...byAtmo.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  list.sort((a, b) => a.temp - b.temp);
  picked.push(list[0]!);
  if (list.length > 1) picked.push(list[list.length - 1]!);
}
const selected = picked.slice(0, 20);

const fixture = {
  note: "Generated by scripts/gen-match-fixture.ts from real journal scans. Regenerate deliberately.",
  generatedAt: new Date().toISOString().slice(0, 10),
  cases: selected.map((c) => {
    const matches = matchDatabaseToScan(db, c.scan, null, null, { includeBacterium: true }).matches;
    return {
      bodyName: c.bodyName,
      scan: trimScan(c.scan),
      confirmedSpecies: c.truth,
      // FSS-only, the scenario the app exists for.
      candidates: matches
        .filter((m) => !m.unlikely)
        .map((m) => m.entry.id)
        .sort(),
      // The demoted tier, pinned separately: a change that moves a species between the two tiers is
      // exactly the kind of change this fixture exists to make visible.
      unlikely: matches
        .filter((m) => m.unlikely)
        .map((m) => m.entry.id)
        .sort(),
    };
  }),
};

const outDir = path.join(root, "tests", "fixtures");
mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, "match-golden.json");
writeFileSync(outPath, `${JSON.stringify(fixture, null, 2)}\n`, "utf8");

const total = fixture.cases.reduce((s, c) => s + c.candidates.length, 0);
const totalUnlikely = fixture.cases.reduce((s, c) => s + c.unlikely.length, 0);
console.log(`wrote ${outPath}`);
console.log(
  `  ${fixture.cases.length} bodies, ${total} shown + ${totalUnlikely} unlikely candidate rows, atmospheres: ${[...byAtmo.keys()].join(", ")}`,
);
