/**
 * Short gameplay tips for newer commanders (and a few advanced). Rotated in the header.
 * Drawn from common ED advice; verify in-game as patches change behaviour.
 */
export const ELITE_TIPS: readonly string[] = [
  "Bind Discovery Scanner, FSS, and DSS to comfortable keys in Analysis Mode.",
  "Honk every new system — it pays and reveals bodies for the FSS.",
  "FSS: follow signal spikes; zoom until the body resolves, then scan.",
  "DSS high-value worlds (ELW/WW/AW) before leaving a system if you want max credits.",
  "Fuel scoop only when heat is under control; zero throttle near stars.",
  "KGB FOAM at the star — remember scoopable classes for safer routing.",
  "Neutron stars boost FSD range in jet cones — carry AFMUs if you chain boosts.",
  "White dwarfs give a smaller boost; cone is tighter — approach carefully.",
  "Black holes never scoop; note them for supercharge plotters anyway.",
  "Run with a fuel scoop sized for your ship — running dry ends the trip.",
  "Carry a small cargo rack for limpets if you use mining or repair limpets.",
  "Set “submit to interdiction” in preferences if you want to avoid NPC drag fights while trading.",
  "Submitting then boosting away often beats a protracted interdiction mini-game.",
  "Fixed weapons need practice; gimballed eases aim at the cost of a bit of damage.",
  "Engineering unlocks real power — start with Farseer (FSD) and Todd (multicannons).",
  "Always gather experimental effects materials before rolling if you want a specific odd roll.",
  "Read each engineer’s unlock tab — many need rank, invite, or commodities first.",
  "Inara and other third-party tools help track materials; the game doesn’t spell routes.",
  "Power plant priority to weapons when fighting, to SYS when tanking heat.",
  "Four pips to SYS massively improves shield resistance — learn to pulse them.",
  "Chaff breaks gimbal lock; heatsinks dump fighter heat and help silent running escapes.",
  "Never fly without rebuy — bank balance should cover insured ship cost.",
  "Loans exist but rebuy wisdom: cash buffer first, bling later.",
  "Mission stations show faction influence — stack missions for one faction to flip systems faster.",
  "Failed missions can hurt reputation — abandon before timeout if you can’t finish.",
  "Winged assassination pays well — wing share makes tough targets manageable.",
  "Conflict zones need a faction choice — pick on the ship’s role panel before joining.",
  "AX weapons and modules are mandatory vs Thargoids — don’t bring pure PvE loadouts to scouts.",
  "Guardian modules unlock easier AX progression — plan a guardian site trip once.",
  "Surface megaship data scans: remember your DSS can tag settlements from orbit.",
  "SRV driving: throttle gently; flipping resets faster than fighting physics.",
  "Ship launch area gives partial gravity — ease into full glide on low-G worlds.",
  "Exobiology: genus hints from DSS narrow species; sample twice then analyse once per species.",
  "Two biological signals can mean two genera — check DSS list before assuming duplicates.",
  "First-footfall organics pay huge bonuses — watch WasFootfalled on detailed scans.",
  "Selling exo data at UC clears samples — don’t sell until you mean to cash out.",
  "Odyssey exo uses samples and analyses — death can wipe unsold progress in some flows.",
  "Laser mining: prospector limpet first — without it yields are a guess.",
  "Subsurface and abrasion need the right tools — build a dedicated miner once.",
  "Refinery bins: don’t let them jam; vent low-value chunks if full at a good rock.",
  "Mapped hotspots from DSS show overlap — overlap + good content = profit.",
  "Void opals and LTD booms rotate with patches — patch notes beat stale reddit wealth threads.",
  "Trading: eddb.io-style tools find supply/demand; in-game only shows your bubble.",
  "Smuggling: silent running and heatsinks reduce scan chance approaching stations.",
  "Outposts without large pads ruin Type-9 dreams — check pad size on the system map.",
  "Fleet carriers move markets — locals may empty when a carrier squad jumps out.",
  "Synthesis refills limpets and heatsinks from materials — bind synthesis menu.",
  "Collect materials from HGE signal sources — log in with time left to farm.",
  "Encoded data: scan wakes and settlements; raw: crystalline shards and shooting rocks.",
  "Manufactured: combat zones and ship destruction — pick faction to stabilise drops.",
  "Prospecting planets: volcanic + atmosphere hints sometimes flag bio candidates early.",
  "Terraformables and HMCs can be jackpot bodies — don’t skip FSS on odd classes.",
  "Ringed ELWs exist — rings don’t always mean worthless gas giants.",
  "Map every ELW/WW/AW you discover if tags matter to you — names stick after DSS.",
  "FSS auto exits on some binds — re-open it if the scan didn’t stick.",
  "System security level changes NPC police response — Low sec means more pirates.",
  "Report crimes toggles bounty payouts from police kills — useful in RES sites.",
  "RES High vs Low: higher rank ships in High, not always better spawns — test your tempo.",
  "Combat logging is against ToS online — finish the fight or accept the loss.",
  "Powerplay prep and fortify on weekly cycles — timers matter Thursday mornings UTC historically.",
  "Galnet is optional lore — missions and BGS still work if you ignore headlines.",
  "Permits lock regions — save permit-grinding missions before road trips.",
  "Sol permit needs Federation rank — pick fed missions early if sightseeing Earth matters.",
  "Empire clipper/cutter lines need Imperial rank — same idea, different mission sets.",
  "Rank-up missions appear in superpower-aligned systems — read the passenger mission board too.",
  "Passenger bulk runs can spike exploration rank if you scan along the route.",
  "Screenshot key hides UI — Alt hides orbit lines for cleaner shots.",
  "Night vision reveals terrain on dark worlds — Odyssey and ship alike.",
  "Guardian ruins: bring a point defence if sentinels annoy your SRV.",
  "Decode ancient data with relic towers mapped online — brute forcing wastes time.",
  "Thargoid barnacles yield materials — beware scouts in some areas.",
  "Megaship uplinks: follow mission text; wrong uplink fails stealth scans.",
  "Settlement stealth: avoid sight lines; night and shutdown reactors when objectives allow.",
  "On-foot energy links chain puzzles — bring an upgrade that matches mission tier.",
  "Weapon racks at settlements restock ammo types you already own — plan slots.",
  "Dropship apex taxis exist in Odyssey — treat them as fast travel with limits.",
  "Save suit upgrades before tough fights — medpen and shield regen matter.",
  "Exo gloves change tool speed — read stats beyond the label.",
  "Planetary tech brokers sell unlocks — bring commodities listed in the Codex panels.",
  "Codex shows first discovery payouts historically — compare to your exploration formula apps.",
  "Universal Cartographics sells cartographic data — travel there after long trips.",
  "Neutron plotting tools externalise jumps — validate in-game that your ship can make legs.",
  "Spansh and similar plotters assume scoopable stars — still pack fuel margin.",
  "Supercruise assist reduces fatigue — bind it for long in-system flights.",
  "Orbital cruise lines matter for DSS probe arcs — approach from sensible angles.",
  "DSS probes regenerate — bad throws just waste a few seconds, not the whole map.",
  "Some bodies need more probes — listen for completion ping before leaving DSS.",
  "FSS discovery “value” isn’t paid until you sell — journal tracks scans, UC pays.",
  "Selling exploration data in chunks is fine — totals add; first discover flags are per cmdr.",
  "Engineer pinned blueprints let remote crafting — pin your most-used roll.",
  "Experimental results can brick a module — backup modules before risky clicks.",
  "Power distributor engineering affects boost cadence — not just weapon uptime.",
  "Dirty drives trade heat for speed — learn to manage temps or strip modules.",
  "Armoured power plant reduces heat and module damage — popular on explorers.",
  "Guardian FSD booster is flat ly bonus — worth slot mass on long haul builds.",
  "Detailed surface scanner quality affects probe efficiency — buy the best you can fit.",
  "Autoscan still logs bodies — DSS is the separate mapping minigame.",
  "System map shows belt clusters — skip mapping them unless completionist.",
  "Lagrange clouds and other POIs appear after honk — worth a visual pass.",
  "Notable stellar phenomena can damage shields — throttle before flying inside.",
];
